// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGpr5Mc6DmGqfQYOcwVxNzd6Lu5DrUXNE',
    appId: '1:1007440937952:android:d5c0a35a000cefbe372185',
    messagingSenderId: '1007440937952',
    projectId: 'fir-authetication-c3514',
    storageBucket: 'fir-authetication-c3514.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChBdrwNiQKY4NJFzvtpmjvLjY056cxF_8',
    appId: '1:1007440937952:web:e2953cd49864b897372185',
    messagingSenderId: '1007440937952',
    projectId: 'fir-authetication-c3514',
    authDomain: 'fir-authetication-c3514.firebaseapp.com',
    storageBucket: 'fir-authetication-c3514.firebasestorage.app',
    measurementId: 'G-NKQNBLJMQC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuaRMTmH0YamO_EVMHfSwNQuY3X8NBul0',
    appId: '1:1007440937952:ios:5582221df674b1e1372185',
    messagingSenderId: '1007440937952',
    projectId: 'fir-authetication-c3514',
    storageBucket: 'fir-authetication-c3514.firebasestorage.app',
    androidClientId: '1007440937952-46v20rkf4unplolerqqc6fjaf853kq1i.apps.googleusercontent.com',
    iosClientId: '1007440937952-u5am9bon654071vqhur4njhm9o6uha0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeShop',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuaRMTmH0YamO_EVMHfSwNQuY3X8NBul0',
    appId: '1:1007440937952:ios:5582221df674b1e1372185',
    messagingSenderId: '1007440937952',
    projectId: 'fir-authetication-c3514',
    storageBucket: 'fir-authetication-c3514.firebasestorage.app',
    androidClientId: '1007440937952-46v20rkf4unplolerqqc6fjaf853kq1i.apps.googleusercontent.com',
    iosClientId: '1007440937952-u5am9bon654071vqhur4njhm9o6uha0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChBdrwNiQKY4NJFzvtpmjvLjY056cxF_8',
    appId: '1:1007440937952:web:ead9ecb8cf3a78bb372185',
    messagingSenderId: '1007440937952',
    projectId: 'fir-authetication-c3514',
    authDomain: 'fir-authetication-c3514.firebaseapp.com',
    storageBucket: 'fir-authetication-c3514.firebasestorage.app',
    measurementId: 'G-TJDJ4EHK6L',
  );

}